[MIPS64] Add __SANE_USERSPACE_TYPES__ to asm/types.h for LL64
Allow 64-bit userspace programs to use ll64 types. The define name
comes from commit 2c9c6ce0199a4d252e20c531cfdc9d24e39235c0 (powerpc:
Add __SANE_USERSPACE_TYPES__ to asm/types.h for LL64).

The patch allows to compile perf on MIPS64 and eliminates the following
warnings:

tests/attr.c:74:4: error: format '%llu' expects argument of type 'long
long unsigned int', but argument 6 has type '__u64' [-Werror=format=]

This patch and the above description is from
http://patchwork.linux-mips.org/patch/6890/
which has been accepted upstream but not yet merged into a release.

This patch is required in order to do full builds of mips64 Android.
Without this patch, various external/* projects fail to compile.

Change-Id: I3b86a4cdb037b0322f99245c28d9a2fda60d595d